### ISSUE TITLE
Add Tableau connect example 

### ISSUE THREAD

**Issue by YuriyGavrilov** [voltrondata/flight-sql-server-example#9]
There is no current support Tableau out of the box. 

<img width="584" alt="Снимок экрана 2023-10-30 в 23 06 57" src="https://github.com/voltrondata/flight-sql-server-example/assets/44679014/311c88ae-1958-4083-9249-f655bcabd6e9">

Some kind of sql dialect problems:
```

2023-10-30 23:06:49.952 +0300 (,,,,26,309) grpc-default-executor-10 : ERROR com.tableau.connect.util.GrpcServiceHelper - Failed in getDialectProperties.
java.lang.NullPointerException: null
	at org.apache.arrow.driver.jdbc.ArrowDatabaseMetadata.getSqlInfoEnumOptionAndCacheIfCacheIsEmpty(ArrowDatabaseMetadata.java:758) ~[?:?]
	at org.apache.arrow.driver.jdbc.ArrowDatabaseMetadata.supportsANSI92EntryLevelSQL(ArrowDatabaseMetadata.java:343) ~[?:?]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.getSQL92Level(JDBCProtocolImpl.java:1038) ~[jdbcserver.jar:20232.0.5]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.getDialectPropertiesImpl(JDBCProtocolImpl.java:1168) ~[jdbcserver.jar:20232.0.5]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.getDialectProperties(JDBCProtocolImpl.java:1189) ~[jdbcserver.jar:20232.0.5]
	at com.tableau.connect.service.ProtocolService.getDialectProperties(ProtocolService.java:260) ~[jdbcserver.jar:20232.0.5]
	at com.tableau.connect.grpc.GrpcProtocolService.lambda$getDialectProperties$15(GrpcProtocolService.java:220) ~[jdbcserver.jar:20232.0.5]
	at com.tableau.connect.grpc.GrpcProtocolService.wrap(GrpcProtocolService.java:280) ~[jdbcserver.jar:20232.0.5]
	at com.tableau.connect.grpc.GrpcProtocolService.getDialectProperties(GrpcProtocolService.java:219) ~[jdbcserver.jar:20232.0.5]
	at com.tableau.connect.generated.ProtocolServiceGrpc$MethodHandlers.invoke(ProtocolServiceGrpc.java:1536) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[jdbcserver.jar:20232.0.5]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[jdbcserver.jar:20232.0.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2023-10-30 23:06:49.952 +0300 (,,,,26,309) grpc-default-executor-10 : INFO  com.tableau.connect.grpc.GrpcProtocolService - End local request 309 /getDialectProperties.
2023-10-30 23:06:49.953 +0300 (,,,,26,310) grpc-default-executor-10 : INFO  com.tableau.connect.grpc.GrpcProtocolService - Start local request 310 /isConnected.
2023-10-30 23:06:49.953 +0300 (,,,,26,310) grpc-default-executor-10 : INFO  com.tableau.connect.grpc.GrpcProtocolService - End local request 310 /isConnected.
2023-10-30 23:06:49.954 +0300 (,,,,26,311) grpc-default-executor-10 : INFO  com.tableau.connect.grpc.GrpcProtocolService - Start local request 311 /closeProtocol.
2023-10-30 23:06:49.954 +0300 (,,,,26,311) grpc-default-executor-10 : INFO  com.tableausoftware.jdbc.JDBCProtocolImpl - Closing connection 26.
2023-10-30 23:06:49.955 +0300 (,,,,26,311) grpc-default-executor-10 : INFO  com.tableau.connect.grpc.GrpcProtocolService - End local request 311 /closeProtocol.
```

This could be useful as alternative example:
https://www.kamu.dev/blog/2023-09-datafusion-flightsql/
https://github.com/kamu-data/kamu-cli

**Comment by prmoore77** [comment]
Thanks for raising the issue, we will check it out...

**Comment by prmoore77** [comment]
I *think* my PR fixes this issue by adding more Flight SQL server override methods.  It seems Tableau needs more Primary Key/Foreign Key support, etc. - this PR adds that.  I'll test more thoroughly next week and merge if all works well...

**Comment by YuriyGavrilov** [comment]
@prmoore77 Thx 🙏 I'm looking forward to testing it too 😋 good luck
